# Generated by Django 6.0.4 on 2026-04-30 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instagram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_depan', models.CharField(max_length=10)),
                ('nama_belakang', models.CharField(max_length=10)),
                ('username', models.CharField(max_length=10)),
            ],
        ),
    ]
