# Generated by Django 6.0.4 on 2026-05-14 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sosmed', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagram',
            name='platform',
            field=models.CharField(choices=[('instagram', 'Instagram'), ('tiktok', 'TikTok')], default='instagram', max_length=20),
        ),
        migrations.AlterField(
            model_name='instagram',
            name='nama_belakang',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='instagram',
            name='nama_depan',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='instagram',
            name='username',
            field=models.CharField(max_length=100),
        ),
    ]
